import os
import shutil
from pathlib import Path
from typing import List

from app.core.constants import WORKSPACES_DIR, RAW_DIR_NAME, WIKI_DIR_NAME, OUTPUTS_DIR_NAME, WIKI_CATEGORIES
from app.schemas.workspace import WorkspaceCreate, WorkspaceResponse
from app.utils.slug import generate_slug
from app.core.logger import get_logger

logger = get_logger(__name__)

class WorkspaceService:
    def __init__(self):
        WORKSPACES_DIR.mkdir(parents=True, exist_ok=True)

    def resolve_workspace_path(self, workspace_id: str) -> Path:
        """Resolve and validate a workspace path against traversal."""
        path = (WORKSPACES_DIR / workspace_id).resolve()
        if WORKSPACES_DIR.resolve() not in path.parents:
            raise ValueError("Invalid workspace ID")
        if not path.exists():
            raise FileNotFoundError(f"Workspace {workspace_id} not found")
        return path

    def list_workspaces(self) -> List[WorkspaceResponse]:
        workspaces = []
        for entry in WORKSPACES_DIR.iterdir():
            if entry.is_dir():
                workspaces.append(WorkspaceResponse(
                    workspace_id=entry.name,
                    name=entry.name,
                    path=str(entry)
                ))
        return workspaces

    def create_workspace(self, data: WorkspaceCreate) -> WorkspaceResponse:
        workspace_id = generate_slug(data.name)
        workspace_path = WORKSPACES_DIR / workspace_id
        
        if workspace_path.exists():
            raise ValueError(f"Workspace {workspace_id} already exists")
            
        workspace_path.mkdir(parents=True)
        
        # Create raw subfolders
        raw_dir = workspace_path / RAW_DIR_NAME
        raw_dir.mkdir()
        (raw_dir / "pdf").mkdir()
        (raw_dir / "txt").mkdir()
        (raw_dir / "md").mkdir()
        
        # Create wiki subfolders
        wiki_dir = workspace_path / WIKI_DIR_NAME
        wiki_dir.mkdir()
        for cat in WIKI_CATEGORIES:
            (wiki_dir / cat).mkdir()
            
        # Create outputs dir
        (workspace_path / OUTPUTS_DIR_NAME).mkdir()
        
        # Create default files
        self._create_default_files(workspace_path)
        
        return WorkspaceResponse(
            workspace_id=workspace_id,
            name=data.name,
            path=str(workspace_path)
        )
        
    def _create_default_files(self, workspace_path: Path):
        wiki_dir = workspace_path / WIKI_DIR_NAME
        
        with open(wiki_dir / "index.md", "w", encoding="utf-8") as f:
            f.write("---\ntitle: Index\ntype: index\n---\n\n# Index\n\nWelcome to the wiki index.\n")
            
        with open(wiki_dir / "log.md", "w", encoding="utf-8") as f:
            f.write("---\ntitle: Log\ntype: log\n---\n\n# Log\n\nIngest log:\n")
            
        with open(wiki_dir / "overview.md", "w", encoding="utf-8") as f:
            f.write("---\ntitle: Overview\ntype: overview\n---\n\n# Overview\n\nWorkspace overview.\n")
            
        agents_content = """# Workspace Agents Config
This workspace relies on a strict file architecture.

## Structure
- `raw/`: Immutable raw uploaded documents (PDF, TXT, MD). Never modify these.
- `wiki/`: Authoritative synthesized knowledge base generated by Gemini. This is an Obsidian-compatible Vault.
- `outputs/`: Temporary or miscellaneous generated artifacts.

## Wiki Rules
- All pages must use `[[wikilinks]]` for internal navigation.
- All pages must have YAML frontmatter with `title`, `type`, `source_documents`, `related_pages`, `tags`.
- Contradictions across raw documents must be explicitly noted in the synthesized pages.
- `index.md` must be regenerated fully on each ingest.
- `log.md` must be appended to on each ingest.
"""
        with open(workspace_path / "AGENTS.md", "w", encoding="utf-8") as f:
            f.write(agents_content)
