import os
import shutil
from pathlib import Path
from typing import List

from app.core.constants import WORKSPACES_DIR, RAW_DIR_NAME, WIKI_DIR_NAME, OUTPUTS_DIR_NAME, WIKI_CATEGORIES
from app.schemas.workspace import WorkspaceCreate, WorkspaceResponse
from app.utils.slug import generate_slug
from app.core.logger import get_logger

logger = get_logger(__name__)

class WorkspaceService:
    def __init__(self):
        WORKSPACES_DIR.mkdir(parents=True, exist_ok=True)

    def resolve_workspace_path(self, workspace_id: str) -> Path:
        """Resolve and validate a workspace path against traversal."""
        path = (WORKSPACES_DIR / workspace_id).resolve()
        if WORKSPACES_DIR.resolve() not in path.parents:
            raise ValueError("Invalid workspace ID")
        if not path.exists():
            raise FileNotFoundError(f"Workspace {workspace_id} not found")
        return path

    def list_workspaces(self) -> List[WorkspaceResponse]:
        workspaces = []
        for entry in WORKSPACES_DIR.iterdir():
            if entry.is_dir():
                workspaces.append(WorkspaceResponse(
                    workspace_id=entry.name,
                    name=entry.name,
                    path=str(entry)
                ))
        return workspaces

    def create_workspace(self, data: WorkspaceCreate) -> WorkspaceResponse:
        workspace_id = generate_slug(data.name)
        workspace_path = WORKSPACES_DIR / workspace_id
        
        if workspace_path.exists():
            raise ValueError(f"Workspace {workspace_id} already exists")
            
        workspace_path.mkdir(parents=True)
        
        # Create raw subfolders
        raw_dir = workspace_path / RAW_DIR_NAME
        raw_dir.mkdir()
        (raw_dir / "pdf").mkdir()
        (raw_dir / "txt").mkdir()
        (raw_dir / "md").mkdir()
        
        # Create wiki subfolders
        wiki_dir = workspace_path / WIKI_DIR_NAME
        wiki_dir.mkdir()
        for cat in WIKI_CATEGORIES:
            (wiki_dir / cat).mkdir()
            
        # Create outputs dir
        (workspace_path / OUTPUTS_DIR_NAME).mkdir()
        
        # Create default files
        self._create_default_files(workspace_path, data.name)
        
        return WorkspaceResponse(
            workspace_id=workspace_id,
            name=data.name,
            path=str(workspace_path)
        )
        
    def _create_default_files(self, workspace_path: Path, workspace_name: str):
        wiki_dir = workspace_path / WIKI_DIR_NAME
        
        with open(wiki_dir / "index.md", "w", encoding="utf-8") as f:
            f.write("---\ntitle: Index\ntype: index\n---\n\n# Index\n\nWelcome to the wiki index.\n\n<!--\nENFORCED INDEX FORMAT:\n- [[slug]] → category/slug.md\n-->\n")
            
        with open(wiki_dir / "log.md", "w", encoding="utf-8") as f:
            f.write("---\ntitle: Log\ntype: log\n---\n\n# Log\n\nIngest log:\n")
            
        with open(wiki_dir / "overview.md", "w", encoding="utf-8") as f:
            f.write("---\ntitle: Overview\ntype: overview\n---\n\n# Overview\n\nWorkspace overview.\n")
            
        agents_content = f"""# Workspace Agents Config
This workspace relies on a strict file architecture.

## Domain
This workspace is named '{workspace_name}'. Edit this section to
describe the subject matter, audience, and purpose of this workspace.
Example: "This workspace covers academic research papers in machine
learning. Pages should use precise technical language appropriate
for an ML researcher audience."

## Structure
- `raw/`: Immutable raw uploaded documents (PDF, TXT, MD).
  Never modify or reference these by path in wiki content.
- `wiki/`: Authoritative synthesized knowledge base generated by
  Gemini. This is an Obsidian-compatible Vault.
- `outputs/`: Temporary or miscellaneous generated artifacts.

## Wiki Rules

### Frontmatter
Every page must have YAML frontmatter with ALL of these fields:
- `title`: Human-readable title (not a slug)
- `type`: Exactly one of: concept, entity, topic, source, person
- `source_documents`: List of raw filenames this page was derived from
- `related_pages`: List of slugs of closely related wiki pages
- `tags`: List of relevant lowercase tags
- `updated`: Date last modified in YYYY-MM-DD format

### Page Structure
Every non-index page must follow this section order where applicable:
1. A lead paragraph (2-4 sentences) summarising the concept
2. `## Definition` or `## Overview` — core explanation
3. `## Key Properties` or `## Details` — specifics, parameters, variants
4. `## Role in Context` — how it fits into the broader workspace topic
5. `## Related Concepts` — wikilinks to related pages with one-line explanations
6. `## References` — which source documents mention this concept

### Wikilinks
- Use `[[slug]]` for ALL internal references to other wiki pages.
- Only link the first occurrence of a concept per section, not every mention.
- Never wikilink to pages that do not exist in the current index.
- Never wikilink inside YAML frontmatter values.

### Contradictions
When two source documents make conflicting claims, mark it explicitly
using this exact blockquote format so the lint tool can detect it:

> **⚠️ Contradiction:** {{Source A}} states X while {{Source B}} states Y.
> Resolution pending further review.

### Persons and Authors
- Do NOT create individual pages for human persons (authors, researchers).
- All persons are compiled into `entities/authors.md` automatically.
- If a person is mentioned in content, refer to them by plain name only —
  no wikilink, no individual page reference.

### Index and Log
- `index.md` must be fully regenerated on each ingest.
- `log.md` must be appended with a timestamped entry on each ingest.
- `overview.md` is auto-generated — do not manually edit it.

### Quality Rules
- Minimum page length: 150 words for concept/entity/topic pages.
- Do not create stub pages with only frontmatter and no content.
- Prefer merging thin related pages over creating many small pages.
- Avoid restating the page title as the first sentence.
"""
        with open(workspace_path / "AGENTS.md", "w", encoding="utf-8") as f:
            f.write(agents_content)

    def delete_workspace(self, workspace_id: str):
        path = self.resolve_workspace_path(workspace_id)
        shutil.rmtree(path)
        logger.info(f"Deleted workspace: {workspace_id}")
